# ~/.tmuxinator/default.yml

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: riak start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: logs

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: riak stop

name: default
root: <%= Dir.pwd %>

windows:
  - editor:
      # Pull this magic layout from list-windows within tmux
      # since screens are different sizes, this will be up to you to pull/customize.
      # http://stackoverflow.com/questions/9812000
      layout: 778c,238x73,0,0{157x73,0,0,0,80x73,158,0[80x35,158,0,3,80x37,158,36,4]}
      panes:
        - vim
        - bundle exec guard
        -
  - server: bundle exec rails s
  - logs: tail -f log/development.log

