tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

# Text editors
brew "ctags-exuberant"
brew "markdown"
brew "vim"

# Terminal Tools
brew "ack"
brew "amazon-ecs-cli"
brew "awscli"
brew "fzf"
brew "git"
brew "gpg"
brew "gron"
brew "hub"
brew "proctools"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "wget"
cask "aws-vault"

# Application Dependencies
brew "autoconf"
brew "automake"
brew "awslogs"
brew "chruby"
brew "gcc"
brew "imagemagick"
brew "libksba"
brew "memcached"
brew "redis"
brew "ruby-install"
brew "unison"
brew "eugenmayer/dockersync/unox"

# Hashicorp Tools
brew "consul"
brew "nomad"
brew "terraform"
brew "vault"

# Databases
brew "mysql@5.7"
brew "postgresql@9.6"

# Javascript
brew "nvm"
brew "yarn"
