# Text editors
brew "ctags-exuberant"
brew "markdown"

# Terminal Tools
brew "ack"
brew "amazon-ecs-cli"
brew "awscli"
brew "fzf"
brew "git"
brew "gpg"
brew "hub"
brew "proctools"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "wget"

# Application Dependencies
brew "autoconf"
brew "automake"
brew "chruby"
brew "gcc"
brew "imagemagick"
brew "libksba"
brew "memcached"
brew "redis"
brew "ruby-install"

# Hashicorp Tools
brew "nomad"
brew "vault"
brew "consul"
brew "terraform"

# Databases
brew "mysql@5.7"
brew "postgresql@9.6"

# Javascript
brew "nvm"
brew "yarn"
